### ISSUE TITLE
Getting error in Logcat

### ISSUE THREAD

**Issue by shivanipatel** [Odoo-mobile/hr#1]
05-28 12:46:12.374    2935-2935/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.odoo.hr, PID: 2935
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.odoo.hr/com.odoo.OdooActivity}: java.lang.StringIndexOutOfBoundsException: length=38; index=-1
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=38; index=-1
            at java.lang.AbstractStringBuilder.indexAndLength(AbstractStringBuilder.java:207)
            at java.lang.AbstractStringBuilder.deleteCharAt0(AbstractStringBuilder.java:251)
            at java.lang.StringBuffer.deleteCharAt(StringBuffer.java:391)
            at com.odoo.core.orm.OSQLHelper.createStatements(OSQLHelper.java:57)
            at com.odoo.core.orm.OSQLite.onCreate(OSQLite.java:90)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at com.odoo.core.orm.OModel.getReadableDatabase(OModel.java:139)
            at com.odoo.core.orm.OModel.count(OModel.java:918)
            at com.odoo.core.orm.OModel.isEmptyTable(OModel.java:620)
            at com.odoo.core.utils.drawer.DrawerUtils.baseSettingsItems(DrawerUtils.java:80)
            at com.odoo.core.utils.drawer.DrawerUtils.getDrawerItems(DrawerUtils.java:60)
            at com.odoo.OdooActivity.setupDrawerBox(OdooActivity.java:160)
            at com.odoo.OdooActivity.setupDrawer(OdooActivity.java:154)
            at com.odoo.OdooActivity.onCreate(OdooActivity.java:116)
            at android.app.Activity.performCreate(Activity.java:5937)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
05-28 12:46:12.704    1229-1384/? E/ActivityManager﹕ Invalid thumbnail dimensions: 576x576
05-28 13:18:52.187    1229-1292/? E/PMBA﹕ No global metadata in state file!

**Comment by dpr-odoo** [comment]
@shivanipatel This app is under development. It is not ready for use.

**Comment by shivanipatel** [comment]
Okay.
Thank you for your help.
